name: Deploy Production

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy-development" that calls a reusable workflow specifying an input 'env' 
  deploy-development:
    uses:  sandrofi84/mapster-AWS-infrastructure/.github/workflows/deploy.yml@master
    with:
      env: prod
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}